### PR TITLE
add openSUSE install instructions

### PR DESCRIPTION
**Pull request by ederag**
As suggested by https://github.com/sqlitebrowser/sqlitebrowser/pull/1792#issuecomment-470772374
Thanks !

### CODE REVIEW

**Comment by justinclift** [comment]
Excellent.  Thanks heaps for this too @ederag. :smile:

**Comment by justinclift** [comment]
Oops.  I haven't set up automatic deployment of changes here, and I don't have remote access to the server until (probably) tomorrow.

Um... there's going to be a delay until this is live.  Sorry @ederag. :scream:

**Comment by ederag** [comment]
Thanks for merging. No hurry at all :smile:

**Comment by ederag** [comment]
Confirmed, https://sqlitebrowser.org/dl/ has been correctly updated, thanks !

**Pull request merged**
